export const START = 'START'
export const STOP = 'STOP'
export const SET_NOTE = 'SET_NOTE'
export const GET_RECORDS = 'GET_RECORDS'
export const ADD_RECORD = 'ADD_RECORD'
export const DELETE_RECORD = 'DELETE_RECORD'
